name: test/CI_dev
on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: self-hosted
    container:
      image: node
    steps:
      - run: yarn --version
      - run: sleep 30
  build2:
    runs-on: self-hosted
    container:
      image: node
    steps:
      - run: yarn --version
      - run: sleep 30
