name: CI
on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: [ubuntu-latest]
    environment: test
    steps:
      - run: echo "${{ toJSON(github) }}"
      - run: echo "${{ toJSON(job) }}"
      - run: echo "finish"
