name: CI
on:
  workflow_dispatch:
    inputs:
      param1:
        type: string
        required: true
      param2:
        type: boolean
      param3:
        type: choice
        options:
          - hoge
          - moge
          - huga        
        
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: echo "${{ github.event.inputs.param1 }}"
      - run: echo "${{ github.event.inputs.param2 }}"
      - run: echo "${{ github.event.inputs.param3 }}"
      - run: sleep 30
      - run: echo "finish"
